# Paths
$scriptsDir = $HOME/.config/hypr/themes/mac/scripts
$screenshotPath = $(xdg-user-dir PICTURES)/Screenshots


###################
### KEYBINDINGS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Spotlight
bind = $mainMod, space, exec, $menu

# System fundamentals
bind = $mainMod SHIFT, Q, exit, # Log out
bind = $mainMod, Q, exec, $scriptsDir/close_window.sh # Close window
bind = CONTROL $mainMod, F, exec, $scriptsDir/maximize_window.sh

bind = $mainMod, E, exec, $fileManager # Open file manager
bind = $mainMod, return, exec, $terminal # Open terminal

# Moving between workspaces
bind = CONTROL, left, workspace, m-1
bind = CONTROL, right, workspace, m+1

# Screenshots
bind = $mainMod SHIFT, 3, exec, hyprshot -m output -o $screenshotPath # Full screenshot
bind = $mainMod SHIFT, S, exec, hyprshot -m region -o $screenshotPath # Screenshot by region

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# -----------------

bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Move window position
bind = SUPER SHIFT, left, swapwindow, l
bind = SUPER SHIFT, right, swapwindow, r
bind = SUPER SHIFT, up, swapwindow, u
bind = SUPER SHIFT, down, swapwindow, d

# Resize active window
bind = SUPER, minus, resizeactive, -100 0
bind = SUPER, plus, resizeactive, 100 0
bind = SUPER SHIFT, minus, resizeactive, 0 -100
bind = SUPER SHIFT, plus, resizeactive, 0 100

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow