################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=eDP-1,preferred,0x0,1
monitor=HDMI-A-1,preferred,auto,1

# Workspace assignment and persistence
workspace = 1, monitor:HDMI-A-1, persistent:true
workspace = 2, monitor:DP-1, persistent:true