source = ./mac-style/src/colors.conf

# ────────────────────────────────────────────────────────────
#  Hyprlock — minimal blur with ringed input
# ────────────────────────────────────────────────────────────

general {
    disable_loading_bar = true
    no_fade_in = false
}

background {
    monitor =
    color = rgba(5, 0, 16, 0)
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.7172
    vibrancy = 0.1696
    vibrancy_darkness = 0
}


animations {
    enabled = false
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = $base_200
    font_size = 25
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -120
    halign = center
    valign = top
    zindex = 5
}

# Hour
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H"):$(date +"%M")"
    color = $base_200
    shadow_size = 3
    shadow_color = $shadow
    shadow_boost = 1.2
    font_size = 100
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -150
    halign = center
    valign = top
    zindex = 5
}

# LOGO
label {
    monitor =
    size = 40
    position = 0, 160
    halign = center
    valign = bottom

    text =  
    color = $base_200
    font_size = 75
}

# USER
label {
    monitor =
    halign = center
    valign = bottom

    text = cmd[update:1000] echo "$USER" | tr '[:lower:]' '[:upper:]'
    color = rgb(255, 255, 255)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, 140
}

input-field {
    monitor =
    size = 135, 25
    position = 0, 100
    halign = center
    valign = bottom

    inner_color= $base_100 
    outer_color = rgba(0, 0, 0, 0)
    outline_thickness = 0

    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    font_color = $base_200

    dots_size=0.30
    dots_spacing=0.2
    dots_center=false

    placeholder_color = $base_200
    placeholder_text = <span size="8pt">Enter Password</span> <span>    </span>
    
    fail_text = <span size="8pt">Enter Password</span> <span>    </span>
    check_color = $base_100
    fail_color= $base_100

    shadow_passes = 0
    fade_on_empty = false
}