plugin {
    hyprbars {
        bar_height = 35

        bar_title_enabled= false
        bar_buttons_alignment=left

        bar_padding=15

        # Close
        hyprbars-button = rgb(ff4040), 15, , ~/.config/hypr/mac-style/scripts/close_window.sh

        #Minimize
        hyprbars-button = rgb(FFCF40), 15, , ~/.config/hypr/mac-style/scripts/minimize_window.sh

        # Maximize
        hyprbars-button = rgb(43FF40), 15, , ~/.config/hypr/mac-style/scripts/maximize_window.sh
        on_double_click= ~/.config/hypr/mac-style/scripts/maximize_window.sh
    }
}